################################################################################
# Based on "Just the Docs"
# Refer to: 
#   https://github.com/just-the-docs/just-the-docs-template/blob/main/README.md#publishing-your-site-on-github-pages)
################################################################################
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

################################################################################
#  -> Theme Suggestions
################################################################################
title: Creator Workflows Now
#description: Hello World Description

url: https://creatorworkflowsnow.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/creatorworkflowsnow


################################################################################
# Just the Docs: 
# Set a path/url to a logo that will be displayed instead of the title
logo: "docs/images/servicenow-logo.png"


################################################################################
# Just the Docs: 
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


################################################################################
mermaid:
# Version of mermaid library
# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
version: "9.1.3"


################################################################################
# Aux links for the upper right navigation
aux_links:
  "ServiceNow.com/Creator-Workflows":
    - "https://www.servicenow.com/workflows/creator-workflows.html"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


################################################################################
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


################################################################################
# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
#markup / liquid-based content.
#footer_content: "Copyright &copy; 2022 <a href=\"https://www.servicenow.com\">ServiceNow</a>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
#gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_repository: "https://github.com/CreatorWorkflowsNow/CreatorWorkflowsNow.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# note: footer_content is deprecated, but still supported. For a better experience we have moved this into an include called _includes/footer_custom.html which will allow for robust markup / liquid-based content.



################################################################################
# Plugins (previously gems:)
################################################################################
# External navigation links
nav_external_links:
  - title: Learn more about Creator Workflows
    url: https://www.servicenow.com/workflows/creator-workflows.html
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Telework Case Management Lab
    url: https://low-code.guide/docs/Telework/Introduction/
    hide_icon: false # set to true to hide the external link icon - defaults to false


################################################################################
# Shao's theme settings from https://github.com/shaoservicenow/travelrequest (12/3/22)
################################################################################

# back_to_top: false
# back_to_top_text: "Back to top"


################################################################################
# Plugins (previously gems:)
################################################################################
#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-include-cache
#  - jekyll-remote-theme 
