################################################################################
# Theme suggestions
#  https://github.com/just-the-docs/just-the-docs-template/blob/main/README.md#publishing-your-site-on-github-pages
################################################################################
title: Creator Workflows Now
description: Hello World Description
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME


################################################################################
# Shao's theme settings from https://github.com/shaoservicenow/travelrequest (12/3/22)
################################################################################
logo: "docs/images/servicenow-logo.png"
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Last Update: 16 October 2022, based on the San Diego release."
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


################################################################################
# Plugins (previously gems:)
################################################################################
#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-include-cache
#  - jekyll-remote-theme 
